version: '3.4'

services:
  flask-server:
    image: flask
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
      - 10001:10001
    volumes:
      - .:/app:cached

# Only needed for testing with local dockerized phabricator:
networks:
  default:
    # name: docker-phabricator_default
    name: docker-phabricator-wmf_default
  